### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by aneurycasado** [aneurycasado/StackStore#20]
Local Storage. What is it? How do I start using it? 

Favicon edit

How do I get the current state of the page in the navbar controller?

How to use ng-repeat to create a grid? 

Flow for unauthenticated users?

Getting names and pictures from google, twitter, and facebook. 

All of admin functionality?

Search functionality? 

Extra Features

**Comment by ryankdwyer** [comment]
Getting names and pictures from google, twitter, and facebook. 
I believe this information is contained in the 'profile' parameter passed in the authentication callback function. Console.log(profile) and you should see the information buried in a json object.
